### ISSUE TITLE
This package collides with an official .NET package - get out of the way!

### ISSUE THREAD

**Issue by ericwj** [ysharplanguage/FastJsonParser#14]
Apparently this [package](http://www.nuget.org/packages/System.Text.Json) collides with the official [System.Text.Json](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.Text.Json) which is in pre-release, but it is anyhow bold that you decided to adopt the naming convention for BCL packages in this project.

Please do file this package under another name. Certainly not starting with System.

**Comment by 304NotModified** [comment]
The nuget link iin the readme also links to Microsofts version? https://www.nuget.org/packages/System.Text.Json

**Comment by 304NotModified** [comment]
Any way, the development looks dead to me.

**Comment by 304NotModified** [comment]
How is this resolved?

**Comment by ericwj** [comment]
I have used `System.Text.Json` and never had any issues. Microsoft pre-empted this I guess, [System.Text.Json](https://www.nuget.org/packages/System.Text.Json) is a Microsoft package. Otherwise still it would be resolved because it is usually already on disk through the fallback mechanism without ever checking nuget.org.
