### ISSUE TITLE
always set a new instance for object data member ?

### ISSUE THREAD

**Issue by sjinny** [ysharplanguage/FastJsonParser#8]
for example :
```
class A
{
    public List< int > datas
    {
        get
        {
            return m_datas;
        }
    }

    private readonly List< int > m_datas= new List< int >();
}
```
when parsing a json as A the datas will always be empty. but if remove the "readonly" and add a setter for datas everything is fine.
could the parsing set a new instance only when getter returned null ?

**Comment by ysharplanguage** [comment]
@sjinny : I expect the behavior you describe. Your backing readonly field is set with its value at construction time of your class A. You could have done it equivalently also in an explicit constructor A(). The parser/deserializer has no idea (and no chance to know) that this has happened, by the time it starts rehydrating the properties of an instance of A freshly constructed this way.
